name: Test and Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
            
            - name: Publish to GitHub Packages
              run: |
                  echo "registry=https://npm.pkg.github.com/xkushyan-rakbank" >> .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
                  echo "@xkushyan-rakbank:registry=https://npm.pkg.github.com" >> .npmrc
                  cat .npmrc
                  npm publish